import { SampleDoc } from "./types";

export const SAMPLE_DOCUMENTS: SampleDoc[] = [
  {
    id: "surat-jalan-01",
    name: "Surat Jalan Material Kemasan",
    type: "Surat Jalan",
    vendor: "PT Logistik Utama Nusantara",
    date: "2026-08-23",
    description: "SJ/2026/08/010 • Suplai Kardus & Palet Gudang",
    sampleImage: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=85",
    mockData: {
      nomor_dokumen: "SJ/2026/08/010",
      jenis_dokumen: "Surat Jalan Pengiriman",
      nama_vendor: "PT Logistik Utama Nusantara",
      tanggal: "2026-08-23",
      nomor_po: "PO-2026-ID-8841",
      metode_pengiriman: "Truk CDD Box (B 9482 UXZ)",
      confidence_score: 99.4,
      processing_time_ms: 1180,
      engine_version: "Veloxis Vision Engine v2.4",
      status: "verified",
      items: [
        {
          sku: "SKU-LOG-01",
          nama_barang: "Kardus Master Box B-Flute (50x40x30 cm)",
          qty: 150,
          satuan: "Box",
          berat_kg: 75.0,
          confidence: 99.8,
          matched_catalog: true,
        },
        {
          sku: "SKU-LOG-02",
          nama_barang: "Bubble Wrap Roll Heavy Duty 1.25m x 50m",
          qty: 20,
          satuan: "Roll",
          berat_kg: 40.0,
          confidence: 99.2,
          matched_catalog: true,
        },
        {
          sku: "SKU-LOG-03",
          nama_barang: "Sticker Label Shipping Thermal 100x150mm",
          qty: 100,
          satuan: "Pack",
          berat_kg: 12.5,
          confidence: 98.9,
          matched_catalog: true,
        },
        {
          sku: "SKU-LOG-04",
          nama_barang: "Palet Plastik Hitam Industri 110x110cm ISO",
          qty: 10,
          satuan: "Unit",
          berat_kg: 150.0,
          confidence: 99.5,
          matched_catalog: true,
        },
      ],
    },
    boundingBoxes: [
      { id: "box-header", label: "Header & Vendor", field: "nama_vendor", x: 6, y: 6, width: 88, height: 16 },
      { id: "box-docno", label: "No. Surat Jalan", field: "nomor_dokumen", x: 55, y: 12, width: 38, height: 7 },
      { id: "box-date", label: "Tanggal Pengiriman", field: "tanggal", x: 55, y: 19, width: 38, height: 6 },
    ],
  },
  {
    id: "surat-jalan-02",
    name: "Surat Jalan Bahan Kemasan",
    type: "Surat Jalan",
    vendor: "PT Megah Jaya Sentosa",
    date: "2026-08-20",
    description: "SJ/2026/08/045 • Pengiriman Lakban & Stretch Film",
    sampleImage: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=1200&q=85",
    mockData: {
      nomor_dokumen: "SJ/2026/08/045",
      jenis_dokumen: "Surat Jalan Pengiriman",
      nama_vendor: "PT Megah Jaya Sentosa",
      tanggal: "2026-08-20",
      nomor_po: "PO-2026-JKT-1904",
      metode_pengiriman: "Armada Vendor Box",
      confidence_score: 98.7,
      processing_time_ms: 1240,
      engine_version: "Veloxis Vision Engine v2.4",
      status: "verified",
      items: [
        {
          sku: "SKU-BOX-100",
          nama_barang: "Kardus Double Wall Heavy Duty Grade A",
          qty: 250,
          satuan: "Pcs",
          berat_kg: 125.0,
          confidence: 99.4,
          matched_catalog: true,
        },
        {
          sku: "SKU-TAPE-02",
          nama_barang: "Lakban Bening 2 Inch Premium 90 Yards",
          qty: 50,
          satuan: "Roll",
          berat_kg: 15.5,
          confidence: 98.2,
          matched_catalog: true,
        },
        {
          sku: "SKU-WRAP-05",
          nama_barang: "Stretch Film Plastic Wrap Industrial 50cm",
          qty: 30,
          satuan: "Roll",
          berat_kg: 60.0,
          confidence: 97.9,
          matched_catalog: true,
        },
      ],
    },
    boundingBoxes: [
      { id: "box-header", label: "Header Vendor", field: "nama_vendor", x: 8, y: 8, width: 84, height: 18 },
      { id: "box-docno", label: "No. Surat Jalan", field: "nomor_dokumen", x: 50, y: 14, width: 42, height: 7 },
    ],
  },
  {
    id: "surat-jalan-03",
    name: "Surat Jalan Perlengkapan Gudang",
    type: "Surat Jalan",
    vendor: "CV Express Trans Logistics",
    date: "2026-08-22",
    description: "SJ/2026/08/112 • Pengiriman Palet & Drum Industri",
    sampleImage: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=1200&q=85",
    mockData: {
      nomor_dokumen: "SJ/2026/08/112",
      jenis_dokumen: "Surat Jalan Pengiriman",
      nama_vendor: "CV Express Trans Logistics",
      tanggal: "2026-08-22",
      nomor_po: "PO-TRANS-4401",
      metode_pengiriman: "Truk Fuso Box",
      confidence_score: 99.1,
      processing_time_ms: 1090,
      engine_version: "Veloxis Vision Engine v2.4",
      status: "verified",
      items: [
        {
          sku: "SKU-PAL-01",
          nama_barang: "Palet Kayu Standar ISO 120x100 Heavy Duty",
          qty: 40,
          satuan: "Unit",
          berat_kg: 720.0,
          confidence: 99.6,
          matched_catalog: true,
        },
        {
          sku: "SKU-DRUM-20",
          nama_barang: "Drum Plastik HDPE Chemical Grade 200L",
          qty: 12,
          satuan: "Drum",
          berat_kg: 240.0,
          confidence: 98.7,
          matched_catalog: true,
        },
        {
          sku: "SKU-CONT-05",
          nama_barang: "Container Box Plastik Industri Stackable",
          qty: 85,
          satuan: "Box",
          berat_kg: 170.0,
          confidence: 99.0,
          matched_catalog: true,
        },
      ],
    },
    boundingBoxes: [
      { id: "box-header", label: "Vendor Title", field: "nama_vendor", x: 10, y: 7, width: 80, height: 15 },
      { id: "box-docno", label: "No. Surat Jalan", field: "nomor_dokumen", x: 60, y: 12, width: 30, height: 6 },
    ],
  },
  {
    id: "surat-jalan-04",
    name: "Surat Jalan Bahan Pangan Inbound",
    type: "Surat Jalan",
    vendor: "PT Global Samudera Distribusi",
    date: "2026-08-21",
    description: "SJ/2026/08/204 • Pengiriman Bahan Pangan Gudang",
    sampleImage: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=85",
    mockData: {
      nomor_dokumen: "SJ/2026/08/204",
      jenis_dokumen: "Surat Jalan Pengiriman",
      nama_vendor: "PT Global Samudera Distribusi",
      tanggal: "2026-08-21",
      nomor_po: "PO-FMCG-9022",
      metode_pengiriman: "Truk CDD Reefer",
      confidence_score: 99.6,
      processing_time_ms: 980,
      engine_version: "Veloxis Vision Engine v2.4",
      status: "verified",
      items: [
        {
          sku: "SKU-FMCG-01",
          nama_barang: "Minyak Goreng Sawit Pouch 2L (Karton 6 Pouch)",
          qty: 300,
          satuan: "Karton",
          berat_kg: 3600.0,
          confidence: 99.8,
          matched_catalog: true,
        },
        {
          sku: "SKU-FMCG-02",
          nama_barang: "Gula Pasir Kristal Putih Premium 1kg (Karton 20)",
          qty: 150,
          satuan: "Karton",
          berat_kg: 3000.0,
          confidence: 99.4,
          matched_catalog: true,
        },
        {
          sku: "SKU-FMCG-03",
          nama_barang: "Tepung Terigu Protein Tinggi Karung 25kg",
          qty: 80,
          satuan: "Karung",
          berat_kg: 2000.0,
          confidence: 99.1,
          matched_catalog: true,
        },
      ],
    },
    boundingBoxes: [
      { id: "box-header", label: "Header Vendor", field: "nama_vendor", x: 7, y: 7, width: 86, height: 16 },
      { id: "box-docno", label: "No. Surat Jalan", field: "nomor_dokumen", x: 52, y: 13, width: 41, height: 7 },
    ],
  },
];
